export const STAT = Object.freeze({
  TOUCHES: "touches",
  ATTACK_WIN: "attackWin",
  ATTACK_OUT: "attackOut",
  ATTACK_NOT_SUCCESSFUL: "attackNotSuccessful",
  TOTAL_ATTACK: "totalAttack",
  ACE: "ace",
  SERVES: "serves",
  SERVES_ERR: "servesErr",
  SERVES_ERR_LINE: "serverErrLine",
  TOTAL_SERVES: "total_serves",
  TOTAL_RECEIVE: "totalRicezione",
  FOUL_DOUBLE: "foul_double",
  FOUL_FOUR_TOUCHES: "foul_four_touches",
  FOUL_RAISED: "foul_raised",
  FOUL_POSITION: "foul_position",
  FOUL_INVASION: "foul_invasion",
  TOTAL_FOUL: "total_foul",
  BALL_LOST: "ball_lost",
  DEF_POS: "defensePos",
  DEF_NEG: "defenseNeg",
  BLOCK_SUCCESSFUL: "blockSuccessful",
  BLOCK_NOT_SUCCESSFUL: "blockNotSuccessful",
  TOTAL_BLOCK: "totalBlock",
  CARD_YELLOW: "card_yellow",
  CARD_RED: "card_red",
  TOTAL_CARD: "totalCard",
  TOTAL_SET_POINTS: "total_set_points",
  SET_POINTS_WIN: "set_points_win",
  SET_POINTS_ERR: "set_points_err",
  SET_POINTS_CANCELLED: "set_points_cancelled",
  TOTAL_MATCH_POINTS: "total_match_points",
  MATCH_POINTS_WIN: "match_points_win",
  MATCH_POINTS_ERR: "match_points_err",
  MATCH_POINTS_CANCELLED: "match_points_cancelled",
  TOTAL_CHANGE: "total_change",
  TOTAL_TIMEOUT: "total_timeout",
  POINTS_PLAYED: "points_played",
  TOTAL_POINTS: "total_points",
});

export const ACTION_MAP = {
  POINT: { stat: STAT.ATTACK_WIN, value: true },
  ACE: { stat: STAT.ACE, value: true },
  OUT: { stat: STAT.ATTACK_OUT, value: false },
  LOST_BALL: { stat: STAT.BALL_LOST, value: false },
  SERVE_ERROR: { stat: STAT.SERVES_ERR, value: false },
  BLOCKED: { stat: STAT.BLOCK_NOT_SUCCESSFUL, value: false },
  DOUBLE: { stat: STAT.FOUL_DOUBLE, value: false },
  "4TOUCHES": { stat: STAT.FOUL_FOUR_TOUCHES, value: false },
  RAISED: { stat: STAT.FOUL_RAISED, value: false },
  POSITION: { stat: STAT.FOUL_POSITION, value: false },
  INVASION: { stat: STAT.FOUL_INVASION, value: false },
};

export const ACTION_EXTRA = {
  POINT: [STAT.TOTAL_ATTACK],
  ACE: [STAT.TOTAL_SERVES, STAT.SERVES],
  OUT: [STAT.TOTAL_ATTACK],
  SERVE_ERROR: [STAT.TOTAL_SERVES],
  BLOCKED: [STAT.TOTAL_BLOCK],
  DOUBLE: [STAT.TOTAL_FOUL],
  "4TOUCHES": [STAT.TOTAL_FOUL],
  RAISED: [STAT.TOTAL_FOUL],
  POSITION: [STAT.TOTAL_FOUL],
  INVASION: [STAT.TOTAL_FOUL],
};

export const ACTION_LABELS = {
  POINT: "Punto!",
  OUT: "Out",
  LOST_BALL: "Palla persa",
  ACE: "⚡ Ace!",
  SERVE_ERROR: "Errore battuta",
  BLOCKED: "Murato",
  DOUBLE: "Doppio fallo",
  "4TOUCHES": "4 tocchi",
  RAISED: "Alzata irregolare",
  POSITION: "Fallo di posizione",
  INVASION: "Invasione",
};

export const ACTION_COLORS = {
  POINT: "#22d47a",
  ACE: "#22d47a",
  SERVE_ERROR: "#f04e4e",
  OUT: "#f04e4e",
  BLOCKED: "#64748b",
  DOUBLE: "#f5c542",
  "4TOUCHES": "#f5c542",
  RAISED: "#f5c542",
  POSITION: "#f5c542",
  INVASION: "#f5c542",
  LOST_BALL: "#64748b",
};
